import Head from 'next/head'
import Image from 'next/image'
import Feed from '../shared/components/feed/Feed'
import Header from '../shared/components/navigation/Header'
import Sidebar from '../shared/components/sidebar/Sidebar'
import Widgets from '../shared/components/widgets/Widgets'

export default function Home() {
  return (
    <div className="h-screen bg-gray-100 dark:bg-gray-900 transition duration-300 overflow-hidden">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>

      <Header />
      <main className="flex">
        <Sidebar/>
        <Feed />
        <Widgets />
      </main>
    </div>
  )
}
